from enum import Enum

class ToolCategory(str, Enum):
    FILESYSTEM = "FILESYSTEM"
    BROWSER = "BROWSER"
    NETWORK = "NETWORK"
    COMMUNICATION = "COMMUNICATION"
    CODE_EXECUTION = "CODE_EXECUTION"
    DATABASE = "DATABASE"
    SYSTEM = "SYSTEM"
    OTHER = "OTHER"

class ActionType(str, Enum):
    READ = "READ"
    WRITE = "WRITE"
    DELETE = "DELETE"
    EXECUTE = "EXECUTE"
    SEND = "SEND"
    UPLOAD = "UPLOAD"
    DOWNLOAD = "DOWNLOAD"
    SEARCH = "SEARCH"
    NAVIGATE = "NAVIGATE"
    QUERY = "QUERY"
    MODIFY = "MODIFY"
    OTHER = "OTHER"

class ThreatType(str, Enum):
    PROMPT_INJECTION = "PROMPT_INJECTION"
    CREDENTIAL_ACCESS = "CREDENTIAL_ACCESS"
    SENSITIVE_DATA_ACCESS = "SENSITIVE_DATA_ACCESS"
    DATA_EXFILTRATION = "DATA_EXFILTRATION"
    DANGEROUS_ACTION = "DANGEROUS_ACTION"
    MALICIOUS_DESTINATION = "MALICIOUS_DESTINATION"
    PRIVILEGE_ESCALATION = "PRIVILEGE_ESCALATION"
    SUSPICIOUS_BEHAVIOR = "SUSPICIOUS_BEHAVIOR"
    UNKNOWN = "UNKNOWN"

class Severity(str, Enum):
    INFO = "INFO"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class SecurityDecisionType(str, Enum):
    ALLOW = "ALLOW"
    BLOCK = "BLOCK"
    REQUIRE_APPROVAL = "REQUIRE_APPROVAL"

class EventType(str, Enum):
    REQUESTED = "REQUESTED"
    ANALYZED = "ANALYZED"
    ALLOWED = "ALLOWED"
    BLOCKED = "BLOCKED"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    EXECUTED = "EXECUTED"
    FAILED = "FAILED"
